# This is a basic workflow to help you get started with Actions
# Doc: https://github.com/dmnemec/copy_file_to_another_repo_action

name: geo-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
      # get the date to use as a commit
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      # UIST DATASETS UPDATED
      # update the repository with the dataset
    - name: Pushes to geo-dataset 
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'out/dataset.json'
        destination_repo: 'geo-conf/geo-dataset-uist'
        destination_folder: ''
        user_email: 'andrea@kaist.ac.kr'
        user_name: 'makinteract'
        commit_message: ${{ steps.date.outputs.date }}

    - name: Pushes the source files of the dataset
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'json'
        destination_repo: 'geo-conf/geo-dataset-uist'
        destination_folder: 'raw'
        user_email: 'andrea@kaist.ac.kr'
        user_name: 'makinteract'
        commit_message: ${{ steps.date.outputs.date }}